Migrate ESXi logger to 20.04

diff --git a/ESXi/ansible/roles/logger/tasks/main.yml b/ESXi/ansible/roles/logger/tasks/main.yml
--- a/ESXi/ansible/roles/logger/tasks/main.yml
+++ b/ESXi/ansible/roles/logger/tasks/main.yml
@@ -62,7 +62,7 @@
   become: yes
   shell: |
       echo "[$(date +%H:%M:%S)]: Running apt-fast install..."
-      apt-fast -qq install -y jq whois build-essential git mysql-server redis-server python-pip unzip htop yq
+      apt-fast -qq install -y jq whois build-essential git mysql-server redis-server python3-pip unzip htop yq libcairo2-dev libjpeg-turbo8-dev libpng-dev libtool-bin libossp-uuid-dev libavcodec-dev libavutil-dev libswscale-dev freerdp2-dev libpango1.0-dev libssh2-1-dev libvncserver-dev libtelnet-dev libssl-dev libvorbis-dev libwebp-dev tomcat9 tomcat9-admin tomcat9-user tomcat9-common
   register: apt_install_prerequisites
   failed_when: "'error' in apt_install_prerequisites.stderr"
 
@@ -88,7 +88,7 @@
     executable: /bin/bash
   become: yes
   shell: |
-    for package in jq whois build-essential git unzip yq mysql-server redis-server python-pip; do
+    for package in jq whois build-essential git unzip yq mysql-server redis-server python3-pip; do
       echo "[$(date +%H:%M:%S)]: [TEST] Validating that $package is correctly installed..."
       # Loop through each package using dpkg
       if ! dpkg -S $package >/dev/null; then
@@ -471,8 +471,8 @@
     cd /opt || exit 1
     git clone https://github.com/OISF/suricata-update.git
     cd /opt/suricata-update || exit 1
-    pip install pyyaml
-    python setup.py install
+    pip3 install pyyaml
+    python3 setup.py install
 
     cp /vagrant/resources/suricata/suricata.yaml /etc/suricata/suricata.yaml
     crudini --set --format=sh /etc/default/suricata '' iface eth1
@@ -530,9 +530,9 @@
   shell: |
     echo "[$(date +%H:%M:%S)]: Installing Zeek..."
     if ! grep 'zeek' /etc/apt/sources.list.d/security:zeek.list; then
-      sh -c "echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/security:zeek.list"
+      sh -c "echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/security:zeek.list"
     fi
-    wget -nv https://download.opensuse.org/repositories/security:zeek/xUbuntu_18.04/Release.key -O /tmp/Release.key
+    wget -nv https://download.opensuse.org/repositories/security:zeek/xUbuntu_20.04/Release.key -O /tmp/Release.key
     apt-key add - </tmp/Release.key &>/dev/null
 
 - name: Install Zeek Packages
@@ -549,7 +549,7 @@
     # Environment variables
     NODECFG=/opt/zeek/etc/node.cfg
     export PATH=$PATH:/opt/zeek/bin
-    pip install zkg==2.1.1
+    pip3 install zkg==2.1.1
     zkg refresh
     zkg autoconfig
     zkg install --force salesforce/ja3
@@ -617,28 +617,37 @@
     executable: /bin/bash
   become: yes
   shell: | 
-    echo "[$(date +%H:%M:%S)]: Installing Guacamole..."
-    cd /opt
-    apt-get -qq install -y libcairo2-dev libjpeg62-dev libpng-dev libossp-uuid-dev libfreerdp-dev libpango1.0-dev libssh2-1-dev libssh-dev tomcat8 tomcat8-admin tomcat8-user
-    wget --progress=bar:force "http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/1.0.0/source/guacamole-server-1.0.0.tar.gz" -O guacamole-server-1.0.0.tar.gz
-    tar -xf guacamole-server-1.0.0.tar.gz && cd guacamole-server-1.0.0
-    ./configure &>/dev/null && make --quiet &>/dev/null && make --quiet install &>/dev/null || echo "[-] An error occurred while installing Guacamole."
+    echo "[$(date +%H:%M:%S)]: Setting up Guacamole..."
+    cd /opt || exit 1
+    echo "[$(date +%H:%M:%S)]: Downloading Guacamole..."
+    wget --progress=bar:force "https://apache.org/dyn/closer.lua/guacamole/1.3.0/source/guacamole-server-1.3.0.tar.gz?action=download" -O guacamole-server-1.3.0.tar.gz
+    tar -xf guacamole-server-1.3.0.tar.gz && cd guacamole-server-1.3.0 || echo "[-] Unable to find the Guacamole folder."
+    echo "[$(date +%H:%M:%S)]: Configuring Guacamole and running 'make' and 'make install'..."
+    ./configure --with-init-dir=/etc/init.d && make --quiet &>/dev/null && make --quiet install &>/dev/null || echo "[-] An error occurred while installing Guacamole."
     ldconfig
-    cd /var/lib/tomcat8/webapps
-    wget --progress=bar:force "http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/1.0.0/binary/guacamole-1.0.0.war" -O guacamole.war
+    cd /var/lib/tomcat9/webapps || echo "[-] Unable to find the tomcat9/webapps folder."
+    wget --progress=bar:force "https://apache.org/dyn/closer.lua/guacamole/1.3.0/binary/guacamole-1.3.0.war?action=download" -O guacamole.war
     mkdir /etc/guacamole
-    mkdir /usr/share/tomcat8/.guacamole
+    mkdir /etc/guacamole/shares
+    sudo chmod 777 /etc/guacamole/shares
+    mkdir /usr/share/tomcat9/.guacamole
     cp /vagrant/resources/guacamole/user-mapping.xml /etc/guacamole/
     cp /vagrant/resources/guacamole/guacamole.properties /etc/guacamole/
     cp /vagrant/resources/guacamole/guacd.service /lib/systemd/system
-    sudo ln -s /etc/guacamole/guacamole.properties /usr/share/tomcat8/.guacamole/
-    sudo ln -s /etc/guacamole/user-mapping.xml /usr/share/tomcat8/.guacamole/
+    sudo ln -s /etc/guacamole/guacamole.properties /usr/share/tomcat9/.guacamole/
+    sudo ln -s /etc/guacamole/user-mapping.xml /usr/share/tomcat9/.guacamole/
+    # Thank you Kifarunix: https://kifarunix.com/install-guacamole-on-debian-11/
+    useradd -M -d /var/lib/guacd/ -r -s /sbin/nologin -c "Guacd User" guacd
+    mkdir /var/lib/guacd
+    chown -R guacd: /var/lib/guacd
+    systemctl daemon-reload
     systemctl enable guacd
-    systemctl enable tomcat8
+    systemctl enable tomcat9
     systemctl start guacd
-    systemctl start tomcat8
-  register: install_guacamole
-  failed_when: "'error' in install_guacamole.stderr"
+    systemctl start tomcat9
+    echo "[$(date +%H:%M:%S)]: Guacamole installation complete!"
+    register: install_guacamole
+    failed_when: "'error' in install_guacamole.stderr"
 
 - name: Postinstall Tasks
   args: 
